name: websyte

services:
  web:
    init: true
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:${PORT}"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
