name: ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3
        with:
          subFolder: web
          push: never
          runCmd: |
            pnpm migrate &&
            pnpm seed &&
            pnpm run check &&
            pnpm run build &&
            pnpm run test
