name: release

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # Updates CHANGELOG.md, creates a tagged release in github and increments the version in package.json
          release-type: node
