name: release

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  metadata:
    runs-on: ubuntu-latest
    outputs:
      tag-name: ${{ steps.metadata.outputs.tag_name }}
      release-created: ${{ steps.metadata.outputs.release_created }}
    steps:
      - name: Update project metadata and the release pull request
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: metadata
        with:
          config-file: release.json
          manifest-file: .manifest.json
